flink:
  job-name: Kafka Source Connector Quickstart
  sources:
    - kafka:
        - data-type: com.regy.quantalink.quickstart.connector.kafka.entity.DcsEvent
          name: kafka-quickstart-source
          bootstrap-servers: kafka.nexdata.stg:9094
          group-id: kafka-quickstart
          topic: test.traceability_v1.data_collection_station
          offset-reset-strategy: EARLIEST