flink:
  job-name: Distribution of Serial Number for ESG

  sources:
    - kafka:
        - data-type: io.github.regychang.flinkify.quickstart.connector.mongo.entity.DcsEvent
          name: kafka-dcs-source
          bootstrap-servers: kafka.nexdata.stg:9094
          group-id: flink-mongo-test
          topic: traceability_v1.data_collection_station
          offset-reset-strategy: EARLIEST
        - data-type: io.github.regychang.flinkify.quickstart.connector.mongo.entity.SensorMap
          name: kafka-sensor-map-source
          bootstrap-servers: kafka.nexdata.stg:9094
          group-id: flink-mongo-test
          topic: traceability.sensormap.test
          offset-reset-strategy: EARLIEST

  sinks:
    - mongo:
        - data-type: io.github.regychang.flinkify.quickstart.connector.mongo.entity.Record
          name: mongo-dcs-production-line-sink
          uri: mongodb://root:nexdata@mongo.nexdata.stg:27017
          database: test
          collection: test
          batch-size: 1000
          batch-interval-ms: 1000
          max-retries: 3
          sink-name: mongo-esg-serial-number-production-line-sink