flink:
  job-name: Kafka Sink Connector Quickstart
  sinks:
    - kafka:
        - input-data-type: java.lang.String
          name: kafka-quickstart-sink
          bootstrap-servers: localhost:9092
          group-id: kafka-quickstart
          topic: kafka-sink-connector-quickstart