flink:
  job-name: Kafka Source Connector Quickstart
  sources:
    - kafka:
        - data-type: java.lang.String
          name: kafka-quickstart-source
          bootstrap-servers: kafka.sdsp-stg.com:9094
          group-id: flink-kafka-quickstart
          topics: new-otdata-telemetry
          offset-reset-strategy: EARLIEST